#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Nemo state=floating
bspc rule -a Brave-browser desktop='^2' state=tiled
bspc rule -a celluloid state=floating
#bspc rule -a Screenkey manage=off

bspc desktop '^2' -l monocle

xrandr --output HDMI-A-0 --mode 1920x1080

picom --config ~/.config/picom/picom.conf &

~/bin/polybar.launch.sh &

feh --bg-fill /home/agus/Pictures/Wallpapers/3135025.jpg &

(sleep 0.25 && paplay /usr/share/mint-artwork/sounds/login.oga)  &

xset s 305 305 & xss-lock --transfer-sleep-lock -- i3lock-fancy &